###################################################################
# Local syslog-ng configuration filter definition [openwrtadmin].
###################################################################
filter f_local_openwrtadmin {
    program("openwrtadmin") or program("openwrt-admind");
};
