[start]
command:/usr/local/etc/rc.d/openwrtadmin onestart
parameters:
type:script
message:starting OpenWrt Admin broker

[stop]
command:/usr/local/etc/rc.d/openwrtadmin onestop
parameters:
type:script
message:stopping OpenWrt Admin broker

[restart]
command:/usr/local/etc/rc.d/openwrtadmin onerestart
parameters:
type:script
message:restarting OpenWrt Admin broker

[status]
command:/usr/local/etc/rc.d/openwrtadmin status; exit 0
parameters:
type:script_output
message:querying OpenWrt Admin broker status

[poll-now]
command:/usr/local/etc/rc.d/openwrtadmin onepollnow
parameters:
type:script_output
message:triggering immediate OpenWrt Admin poll
